### ISSUE TITLE
ESP8266 instead of RTC?

### ISSUE THREAD

**Issue by Ompapamowmow** [dr-mod/pico-solar-system#12]
Would it be possible to use an ESP8266 to fetch Internet time instead of using an RTC? I know RTCs are cheap, I'm just looking for projects to do with the kids using the parts I have on hand. My knowledge of this stuff is very limited.

**Comment by dr-mod** [comment]
Hi @Ompapamowmow, at the moment the software relies on an RTC module and Pico's internal clock. While it's of course possible to adapt the code, it would require to change a couple of functions and make use of the ESP8266 internal clock.
