### ISSUE TITLE
Pico display 2

### ISSUE THREAD

**Issue by Tongans101** [dr-mod/pico-solar-system#15]
Hi

this is a great little system. I have a pico display pack 2. and get an error when I change your code in the main.py to try and get the whole thing working on the display pack 2.

the code I change is simply line one to show  "from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY_2, PEN_RGB565"

and  line 14  to show "display = PicoGraphics(display=DISPLAY_PICO_DISPLAY_2, rotate=0, pen_type=PEN_RGB565)"

I then run it all and get

Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
MemoryError: memory allocation failed, allocating 153600 bytes

my micropython is pretty minimal but I am guess ing there is an issue with memory allocation to the DIsplay pack 2 as it is that much bigger for the pico w to run

any hints or ideas would be appreciated

**Comment by scavone** [comment]
Change your pen type to PEN_RGB332. It uses less colors but allows the code to run on the larger display. I have a working version on the Display Pack 2 but ended up customizing several other lines that dealt with the location of objects to accommodate the larger screen. I wanted to go back and make it more reusable before submitting a pull request but haven’t had the extra time. It’s definitely a fun little project though!
