### ISSUE TITLE
Request: Could you provide some more pics of how/where the RTC is attached?

### ISSUE THREAD

**Issue by markmcgookin** [dr-mod/pico-solar-system#18]
As the title states, I'd love to see how/where you attached the RTC as it was my understanding that the pico display covers all the pins. I've used the pimoroni pico lipo shim and had it in between the pico and the display, but not sure which RTC clock module you are using and how you attached it. 

Thanks

**Comment by ExperiMentor** [comment]
What a display "covers" on a Pico depends on which display you've chosen. My display doesn't physically cover any part of the Pico - just connected by a couple of wires (I2C from memory). An RTC uses different pins.
Or you can get expansion boards that give 2 or 4 complete additional sets of pins.

**Comment by markmcgookin** [comment]
oh, I thought it was the pico display pack from pimoroni that has small headers on it, so you needed to solder headers on your pico and thus 'used' up all your pins even thought they weren't all being actually used by the display

**Comment by dr-mod** [comment]
Hi @markmcgookin, in my case I used a "stackable" RTC module for Pico from Waveshare. You don't need to solder it, but just connect it in the same way you connected your display pack
