### ISSUE TITLE
Could i use a waveshare 1.14 inch based board ST7789VW 

### ISSUE THREAD

**Issue by sgrundmannhs** [dr-mod/pico-solar-system#19]
Hey there,

is it possible to use:
https://www.waveshare.com/wiki/Pico-LCD-1.14

it seems to have similar capabilities.

**Comment by dr-mod** [comment]
Hey @sgrundmannhs, the module I use in the project is built around an ST7789 display. I believe the one from waveshare should be fine as well.

**Comment by ExperiMentor** [comment]
I modified it to use the square screen on a Pico Explorer Base, and it
works fine. In fact, the square allows larger orbits to be shown, and I
simulated the different distances from the sun and added a Kuiper belt.
It's good code, easy to modify and great for learning as you do!

**Comment by dr-mod** [comment]
@ExperiMentor sounds great! Do you have a photo by any chance?

**Comment by ExperiMentor** [comment]
![Orrery](https://github.com/dr-mod/pico-solar-system/assets/8335685/5d3d4e6a-1b15-44a5-94ff-5b42e360f0d1)

**Comment by ExIlIsT** [comment]
thx a lot guys, i give it a try :)
