### ISSUE TITLE
How to set UTC offset on Pico W?

### ISSUE THREAD

**Issue by ashamar** [dr-mod/pico-solar-system#21]
Is there a way to set the UTC offset when using NTP instead of RTC? The instructions all reference the RTC module and looking at main.py, i don't see an obvious way to implement it.

Thanks!

**Comment by dr-mod** [comment]
You could apply the required offset here: https://github.com/dr-mod/pico-solar-system/blob/1af74f3593bab7f4eb6e5bbf38725db289c77938/ntptime.py#L44 In a similar fashion to how it's demonstrated in the instructions. Hope this helps.
