### ISSUE TITLE
OSError: [Errno 5] EIO - When running rtc.set_time(time.time())

### ISSUE THREAD

**Issue by SpoonerUK** [dr-mod/pico-solar-system#3]
I cannot get the RTC to set the time, I don't know what the issue is.

`Entering REPL. Use Control-X to exit.
>
MicroPython v1.15 on 2021-05-20; Raspberry Pi Pico with RP2040
Type "help()" for more information.
>>>
>>> import time
>>> import ds3231
>>> rtc = ds3231.ds3231()
>>> rtc.set_time(time.time())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ds3231.py", line 27, in set_time
OSError: [Errno 5] EIO
>>>`

**Comment by dr-mod** [comment]
Hi, the most probable cause for this is that you Pico can't reach your RTC module. I get the same error if my RTC is not connected.
You could check the connection or replace the module.
