### ISSUE TITLE
Not Turning On

### ISSUE THREAD

**Issue by myprogers** [dr-mod/pico-solar-system#4]
Is this supposed to start automatically? For some reason after I did all the steps my screen is still blank. What should I do?

**Comment by myprogers** [comment]
P.S. the backlight and RGB LED still work just nothing on the screen.

**Comment by crlang44** [comment]
I have not used this yet but I think you'll need to run python3 main.py from the command line to start it

**Comment by myprogers** [comment]
Found out what happened. Turns out I used the wrong MicroPython UF2 file instead of the one from Pimoroni. Apparently only the one from Pimoroni works with the Pico Display Pack and not the UF2 file from Raspberry Pi's website.
